# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Less verbose and more shell friendly Terraform"
  homepage "https://github.com/dex4er/tf"
  version "2.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dex4er/tf/releases/download/v2.11.0/tf-darwin-amd64"
      sha256 "e981bcd23d2454cbce6f131d5dd3133ea9f7b953c6883590a8dc92640448a457"

      def install
        bin.install "tf-darwin-amd64" => "tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dex4er/tf/releases/download/v2.11.0/tf-darwin-arm64"
      sha256 "b98ce9802a2f71843f617932d1016da0a0feb345d1f53102d961febeac9f78bb"

      def install
        bin.install "tf-darwin-arm64" => "tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dex4er/tf/releases/download/v2.11.0/tf-linux-amd64"
        sha256 "eaf1372c6f6e53b386ce82a9933cf25490c6cf15dd4ad3f10522483710a4f9ce"

        def install
          bin.install "tf-linux-amd64" => "tf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dex4er/tf/releases/download/v2.11.0/tf-linux-arm64"
        sha256 "62537f532706a55d6cbc4fa071cdd5819df27598a3376990de445712c0bfc719"

        def install
          bin.install "tf-linux-arm64" => "tf"
        end
      end
    end
  end
end
