# This file was generated by GoReleaser. DO NOT EDIT.
cask "tf" do
  version "2.14.0"

  on_macos do
    on_intel do
      sha256 "db02e708c30561741ae7b26570891b7847c3e40b6711317e28ae06bc09ae0ce0"
      url "https://github.com/dex4er/tf/releases/download/v2.14.0/tf-darwin-amd64"
      binary "tf-darwin-amd64", target: "tf"
    end
    on_arm do
      sha256 "e1e5c1a944b1a7802f2d59b614e6e1458c5f21372c7592b04e999615a3b06b52"
      url "https://github.com/dex4er/tf/releases/download/v2.14.0/tf-darwin-arm64"
      binary "tf-darwin-arm64", target: "tf"
    end
  end

  on_linux do
    on_intel do
      sha256 "02128adbae613b9e12697bf85f47bfd87521646833255b8388e29e3fc61e7b25"
      url "https://github.com/dex4er/tf/releases/download/v2.14.0/tf-linux-amd64"
      binary "tf-linux-amd64", target: "tf"
    end
    on_arm do
      sha256 "e28a193d3e8d1c87549339a2e15880f99b10ab28d54f9f5ab36c392893678a42"
      url "https://github.com/dex4er/tf/releases/download/v2.14.0/tf-linux-arm64"
      binary "tf-linux-arm64", target: "tf"
    end
  end

  name "tf"
  desc "Less verbose and more shell friendly Terraform"
  homepage "https://github.com/dex4er/tf"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
