# This file was generated by GoReleaser. DO NOT EDIT.
cask "tf" do
  version "2.14.1"

  on_macos do
    on_intel do
      sha256 "ae0756e81c3e3bfdee8601e1a0d0b8e19b53562e57dd7a269fc800e53acc5319"
      url "https://github.com/dex4er/tf/releases/download/v#{version}/tf-darwin-amd64"
      binary "tf-darwin-amd64", target: "tf"
    end
    on_arm do
      sha256 "325b9cb60157ad3cfeda43b2ece35414522ec133c42e20895659352c91077cad"
      url "https://github.com/dex4er/tf/releases/download/v#{version}/tf-darwin-arm64"
      binary "tf-darwin-arm64", target: "tf"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9b7339a03c41d5acec9273fcd63992636ff7e556eb3d9debd152471f4339e8d"
      url "https://github.com/dex4er/tf/releases/download/v#{version}/tf-linux-amd64"
      binary "tf-linux-amd64", target: "tf"
    end
    on_arm do
      sha256 "59fff338a766f82922a7c3eb6b02fdbcac16eedd7244742bd1f24e2dd57c1a99"
      url "https://github.com/dex4er/tf/releases/download/v#{version}/tf-linux-arm64"
      binary "tf-linux-arm64", target: "tf"
    end
  end

  name "tf"
  desc "Less verbose and more shell friendly Terraform"
  homepage "https://github.com/dex4er/tf"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
